name:                Kairos
version:             0.3.7
github:              "leofltt/Kairos"
license:             MIT
author:              "Leo Foletto"
maintainer:          "flttleonardo@gmail.com"
copyright:           "2018, Leonardo Foletto"

extra-source-files:
- README.md
- ChangeLog.md
- Kairos.csd

synopsis:            Audio live coding library
category:            Sound

description:         Please see the README on GitHub at <https://github.com/leofltt/Kairos#readme>

dependencies:
- base >= 4.7 && < 5
- time
- stm
- random
- network
- bytestring
- containers
- transformers
- csv
- vivid-osc 
- hspec 

library:
  source-dirs: src

  exposed-modules:
  - Kairos.Lib
  - Kairos.Performance
  - Kairos.Clock
  - Kairos.TimePoint
  - Kairos.Pfield
  - Kairos.PfPat
  - Kairos.Instrument
  - Kairos.Network
  - Kairos.Player
  - Kairos.Utilities
  - Kairos.Scales
  - Kairos.Markov
  - Kairos.Euclidean
  - Kairos.Star.Rhythm.Spark
  - Kairos.Star.Rhythm.L
  - Kairos.Test.TimePoint
  - Kairos.Test.Clock


#  other-modules:

#executables:
#  Kairos-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - Kairos

tests:
  Kairos-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Kairos
